apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-demo
  namespace: jadice
  labels:
    # connection to the pods
    app: prometheus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-demo
  template:
    metadata:
      labels:
        app: prometheus-demo
    spec:
      containers:
        - name: prometheus-demo
          imagePullPolicy: Always
          # getting the newest image
          image: */prometheues-test-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi