apiVersion: v1
kind: Service
metadata:
  # the name for the service
  name: prometheus-demo
  namespace: jadice
  labels:
    app: prometheus-demo
spec:
  selector:
    app: prometheus-demo
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
